---

- name: "Upgrade Existing packages."
  become: true
  apt:
    upgrade: "yes"

- name: "Installation of Requiered dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Intallation of pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
